sudo: false
language: node_js
node_js:
  - 0.10
  - 0.12
  - iojs
notifications:
  irc:
    nick: gulp-slm
    channels:
      - irc.uriirc.org:16667#hyeon
    template:
      - "#%{build_number} %{result}, %{build_url}"
    skip_join: true
after_script:
  - mocha --require blanket -R mocha-lcov-reporter | coveralls
